name: Build and Test
on:
  push:
    branches: 
      - main
      - update-docker-file
    pull_request:
      branches: 
        - main
        - update-docker-file
jobs:
  build_test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: webdevops
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
         - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
     - name: Checkout code
       uses: actions/checkout@v4

     - name: setup python
       uses: actions/setup-python@v5
       with:
        python-version: '3.9'

     - name: Install dependencies
       run: pip install -r requirements.txt

     - name: Run flake8 linter
       run: |
          pip install flake8
          flake8 .

     - name: black check
       run: |
          pip install black
          black --check .

     - name: Run tests
       env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_DB: webdevops
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/webdevops
       run: python manage.py test